"""
All Windows 10/11 bloatware, services, and tweaks definitions.
W11-only items are marked with  "win11": True
"""

BLOATWARE_APPS = [
    {
        "id": "teams",
        "name": "Microsoft Teams",
        "package": "MicrosoftTeams",
        "description": "Aplicación de videoconferencias preinstalada",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "skype",
        "name": "Skype",
        "package": "Microsoft.SkypeApp",
        "description": "Cliente de videollamadas clásico de Microsoft",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "cortana",
        "name": "Cortana",
        "package": "Microsoft.549981C3F5F10",
        "description": "Asistente virtual de Microsoft",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "xbox",
        "name": "Xbox App",
        "package": "Microsoft.XboxApp",
        "description": "Aplicación de Xbox (no necesaria si no juegas en Xbox)",
        "risk": "low",
        "recommended": False,
    },
    {
        "id": "xbox_gamebar",
        "name": "Xbox Game Bar",
        "package": "Microsoft.XboxGamingOverlay",
        "description": "Overlay de juego con captura de pantalla y chat",
        "risk": "medium",
        "recommended": False,
    },
    {
        "id": "xbox_identity",
        "name": "Xbox Identity Provider",
        "package": "Microsoft.XboxIdentityProvider",
        "description": "Servicio de identidad de Xbox",
        "risk": "medium",
        "recommended": False,
    },
    {
        "id": "xbox_speech",
        "name": "Xbox Speech To Text",
        "package": "Microsoft.XboxSpeechToTextOverlay",
        "description": "Overlay de voz de Xbox",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "bing_weather",
        "name": "El Tiempo (MSN)",
        "package": "Microsoft.BingWeather",
        "description": "Widget del tiempo de Bing",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "bing_news",
        "name": "Noticias (MSN)",
        "package": "Microsoft.BingNews",
        "description": "Lector de noticias de Bing",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "bing_finance",
        "name": "Dinero (MSN)",
        "package": "Microsoft.BingFinance",
        "description": "App de finanzas de Bing",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "bing_sports",
        "name": "Deportes (MSN)",
        "package": "Microsoft.BingSports",
        "description": "App de deportes de Bing",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "solitaire",
        "name": "Microsoft Solitaire",
        "package": "Microsoft.MicrosoftSolitaireCollection",
        "description": "Colección de juegos de cartas",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "candy_crush",
        "name": "Candy Crush / King Games",
        "package": "king.com",
        "description": "Juegos de King preinstalados",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "3d_builder",
        "name": "3D Builder",
        "package": "Microsoft.3DBuilder",
        "description": "Aplicación de modelado 3D básico",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "3d_viewer",
        "name": "3D Viewer",
        "package": "Microsoft.Microsoft3DViewer",
        "description": "Visor de modelos 3D",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "mixed_reality",
        "name": "Mixed Reality Portal",
        "package": "Microsoft.MixedReality.Portal",
        "description": "Portal de realidad mixta (solo útil con hardware VR)",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "onenote",
        "name": "OneNote (Store)",
        "package": "Microsoft.Office.OneNote",
        "description": "Versión UWP de OneNote",
        "risk": "low",
        "recommended": False,
    },
    {
        "id": "maps",
        "name": "Mapas de Windows",
        "package": "Microsoft.WindowsMaps",
        "description": "App de mapas integrada",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "people",
        "name": "Contactos (People)",
        "package": "Microsoft.People",
        "description": "App de contactos integrada",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "get_started",
        "name": "Comenzar / Tips",
        "package": "Microsoft.Getstarted",
        "description": "App de bienvenida y tutoriales de Windows",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "feedback_hub",
        "name": "Centro de Opiniones",
        "package": "Microsoft.WindowsFeedbackHub",
        "description": "App para enviar feedback a Microsoft",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "print3d",
        "name": "Imprimir en 3D",
        "package": "Microsoft.Print3D",
        "description": "Herramienta de impresión 3D",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "groove_music",
        "name": "Groove Music",
        "package": "Microsoft.ZuneMusic",
        "description": "Reproductor de música de Microsoft",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "movies_tv",
        "name": "Películas y TV",
        "package": "Microsoft.ZuneVideo",
        "description": "Reproductor de vídeo de Microsoft",
        "risk": "low",
        "recommended": False,
    },
    {
        "id": "wallet",
        "name": "Microsoft Wallet",
        "package": "Microsoft.Wallet",
        "description": "Servicio de pagos de Microsoft",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "sticky_notes",
        "name": "Notas Rápidas",
        "package": "Microsoft.MicrosoftStickyNotes",
        "description": "Post-its digitales",
        "risk": "low",
        "recommended": False,
    },
    {
        "id": "alarms",
        "name": "Alarmas y Reloj",
        "package": "Microsoft.WindowsAlarms",
        "description": "App de alarmas del sistema",
        "risk": "low",
        "recommended": False,
    },
    {
        "id": "camera",
        "name": "Cámara",
        "package": "Microsoft.WindowsCamera",
        "description": "App de cámara integrada",
        "risk": "low",
        "recommended": False,
    },
    {
        "id": "your_phone",
        "name": "Tu Teléfono",
        "package": "Microsoft.YourPhone",
        "description": "Sincronización con teléfono Android",
        "risk": "low",
        "recommended": False,
    },
    {
        "id": "advertising_id_app",
        "name": "Microsoft Advertising",
        "package": "Microsoft.Advertising.Xaml",
        "description": "SDK de publicidad de Microsoft",
        "risk": "low",
        "recommended": True,
    },
    # ── Windows 11 only ───────────────────────────────────────────────────
    {
        "id": "w11_copilot",
        "name": "Microsoft Copilot",
        "package": "Microsoft.Copilot",
        "description": "Asistente de IA de Microsoft integrado en W11",
        "risk": "low",
        "recommended": True,
        "win11": True,
    },
    {
        "id": "w11_clipchamp",
        "name": "Clipchamp (Editor de vídeo IA)",
        "package": "Microsoft.Clipchamp",
        "description": "Editor de vídeo con IA generativa integrada",
        "risk": "low",
        "recommended": True,
        "win11": True,
    },
    {
        "id": "w11_paint_cocreator",
        "name": "Paint (con Cocreator IA)",
        "package": "Microsoft.Paint",
        "description": "La versión W11 de Paint incluye generación de imágenes por IA",
        "risk": "low",
        "recommended": False,
        "win11": True,
    },
    {
        "id": "w11_dev_home",
        "name": "Dev Home",
        "package": "Microsoft.DevHome",
        "description": "Panel de desarrollador con GitHub Copilot integrado",
        "risk": "low",
        "recommended": True,
        "win11": True,
    },
    {
        "id": "w11_outlook_new",
        "name": "Outlook nuevo (con Copilot IA)",
        "package": "Microsoft.OutlookForWindows",
        "description": "Nuevo Outlook con IA de Copilot para redacción y resúmenes de emails",
        "risk": "low",
        "recommended": True,
        "win11": True,
    },
    {
        "id": "w11_phone_link",
        "name": "Vinculación con el Teléfono (Phone Link)",
        "package": "Microsoft.YourPhone",
        "description": "Versión W11 con sugerencias de contenido basadas en IA",
        "risk": "low",
        "recommended": True,
        "win11": True,
    },
]

SERVICES = [
    {
        "id": "diagtrack",
        "name": "Telemetría (DiagTrack)",
        "service": "DiagTrack",
        "description": "Recopila y envía datos de diagnóstico a Microsoft",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "dmwappushservice",
        "name": "WAP Push (dmwappushsvc)",
        "service": "dmwappushservice",
        "description": "Servicio de mensajes WAP, relacionado con telemetría",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "sysmain",
        "name": "SysMain (SuperFetch)",
        "service": "SysMain",
        "description": "Precarga aplicaciones en RAM. En SSDs puede perjudicar el rendimiento",
        "risk": "medium",
        "recommended": False,
        "gaming": True,
    },
    {
        "id": "wsearch",
        "name": "Windows Search",
        "service": "WSearch",
        "description": "Indexa archivos para búsqueda rápida. Consume CPU/disco en segundo plano",
        "risk": "medium",
        "recommended": False,
        "gaming": True,
    },
    {
        "id": "wuauserv",
        "name": "Windows Update",
        "service": "wuauserv",
        "description": "Servicio de actualizaciones automáticas",
        "risk": "high",
        "recommended": False,
        "gaming": False,
    },
    {
        "id": "bits",
        "name": "BITS (Transferencias en 2º plano)",
        "service": "BITS",
        "description": "Descarga actualizaciones en segundo plano",
        "risk": "medium",
        "recommended": False,
        "gaming": True,
    },
    {
        "id": "print_spooler",
        "name": "Cola de Impresión (Spooler)",
        "service": "Spooler",
        "description": "Gestiona las impresiones. Desactívalo si no tienes impresora",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "fax",
        "name": "Fax",
        "service": "Fax",
        "description": "Servicio de fax. Completamente innecesario en la mayoría de casos",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "remoteregistry",
        "name": "Registro Remoto",
        "service": "RemoteRegistry",
        "description": "Permite modificar el registro de forma remota. Riesgo de seguridad",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "lfsvc",
        "name": "Servicio de Geolocalización",
        "service": "lfsvc",
        "description": "Servicio de ubicación GPS del sistema",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "wbiosrvc",
        "name": "Biometría de Windows",
        "service": "WbioSrvc",
        "description": "Gestiona lectores de huella dactilar y reconocimiento facial",
        "risk": "low",
        "recommended": False,
        "gaming": False,
    },
    {
        "id": "icssvc",
        "name": "Zona de acceso móvil (Hotspot)",
        "service": "icssvc",
        "description": "Permite compartir conexión por WiFi desde el PC",
        "risk": "low",
        "recommended": False,
        "gaming": True,
    },
    {
        "id": "lmhosts",
        "name": "Ayuda de NetBIOS TCP/IP",
        "service": "lmhosts",
        "description": "Resolución de nombres NetBIOS en red local, obsoleto",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "tabletinputservice",
        "name": "Servicio de Panel Táctil",
        "service": "TabletInputService",
        "description": "Soporte para teclado táctil y escritura a mano. Innecesario sin pantalla táctil",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "xblauthmanager",
        "name": "Xbox Auth Manager",
        "service": "XblAuthManager",
        "description": "Autenticación de Xbox Live",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "xblgamesave",
        "name": "Xbox Live Game Save",
        "service": "XblGameSave",
        "description": "Sincroniza guardadas de Xbox Live",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "xboxnetapisvc",
        "name": "Xbox Network API",
        "service": "XboxNetApiSvc",
        "description": "API de red de Xbox Live",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "retaildemo",
        "name": "Modo Demo de Tienda",
        "service": "RetailDemo",
        "description": "Modo demostración de tienda. Completamente inútil en uso normal",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "mapsbrokersvc",
        "name": "Gestor de Mapas",
        "service": "MapsBroker",
        "description": "Descarga mapas offline para la app Mapas",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "sharedaccess",
        "name": "Conexión Compartida a Internet (ICS)",
        "service": "SharedAccess",
        "description": "Permite compartir la conexión a Internet entre equipos",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    # ── Windows 11 only ───────────────────────────────────────────────────
    {
        "id": "w11_aihelpersvc",
        "name": "AI Helper Service",
        "service": "AIXHelper",
        "description": "Servicio auxiliar de IA del sistema (W11 24H2+). Consumo constante en segundo plano",
        "risk": "low",
        "recommended": True,
        "gaming": True,
        "win11": True,
    },
    {
        "id": "w11_cbdhsvc",
        "name": "Portapapeles en la nube (cbdhsvc)",
        "service": "cbdhsvc",
        "description": "Sincroniza el portapapeles entre dispositivos. Usa IA para sugerencias",
        "risk": "low",
        "recommended": True,
        "gaming": True,
        "win11": True,
    },
    {
        "id": "w11_wisvc",
        "name": "Windows Insider Service (wisvc)",
        "service": "wisvc",
        "description": "Envía datos al programa Insider de Microsoft. Activo incluso sin ser Insider",
        "risk": "low",
        "recommended": True,
        "gaming": True,
        "win11": True,
    },
    {
        "id": "w11_perceptionsimulation",
        "name": "Perception Simulation Service",
        "service": "perceptionsimulation",
        "description": "Servicio de simulación perceptual para IA y realidad mixta (W11)",
        "risk": "low",
        "recommended": True,
        "gaming": True,
        "win11": True,
    },
    {
        "id": "w11_wemsvc",
        "name": "Windows Experience Service (wemsvc)",
        "service": "wemsvc",
        "description": "Recopila datos de uso para personalización con IA (W11)",
        "risk": "low",
        "recommended": True,
        "gaming": True,
        "win11": True,
    },
    {
        "id": "w11_storsvc",
        "name": "Storage Service / Recall (StorSvc)",
        "service": "StorSvc",
        "description": "Gestiona Recall y almacenamiento de capturas de IA en W11",
        "risk": "medium",
        "recommended": True,
        "gaming": True,
        "win11": True,
    },
    {
        "id": "w11_camsvc",
        "name": "Capability Access Manager (camsvc)",
        "service": "camsvc",
        "description": "Gestiona permisos de acceso de apps de IA (cámara, micrófono, ubicación)",
        "risk": "low",
        "recommended": False,
        "gaming": True,
        "win11": True,
    },
]

TWEAKS = [
    # ── Privacidad ────────────────────────────────────────────────────────
    {
        "id": "telemetry_reg",
        "name": "Telemetría",
        "category": "privacy",
        "description": "Nivel de telemetría enviada a Microsoft (OFF = nivel mínimo 0)",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "cortana_search",
        "name": "Cortana en búsquedas",
        "category": "privacy",
        "description": "Integración de Cortana en la barra de búsqueda del sistema",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "activity_history",
        "name": "Historial de Actividad",
        "category": "privacy",
        "description": "Línea de tiempo y registro de actividad de Windows (OFF = desactivado)",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "advertising_id",
        "name": "ID de Publicidad",
        "category": "privacy",
        "description": "Identificador único de publicidad de Microsoft (OFF = desactivado)",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "location_tracking",
        "name": "Rastreo de Ubicación",
        "category": "privacy",
        "description": "Servicio de localización del sistema (OFF = desactivado)",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "feedback_freq",
        "name": "Solicitudes de Feedback",
        "category": "privacy",
        "description": "Peticiones periódicas de valoración a Microsoft (OFF = sin solicitudes)",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "notifications",
        "name": "Notificaciones del sistema",
        "category": "privacy",
        "description": "Centro de notificaciones y notificaciones de apps (OFF = desactivado)",
        "risk": "low",
        "recommended": False,
        "gaming": True,
    },
    {
        "id": "error_reporting",
        "name": "Informes de Error de Windows",
        "category": "privacy",
        "description": "Envío automático de informes de error a Microsoft (OFF = bloqueado)",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "remote_assistance",
        "name": "Asistencia Remota",
        "category": "privacy",
        "description": "Función de control remoto de Windows (OFF = desactivado)",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "news_interests",
        "name": "Noticias e Intereses (Barra de Tareas)",
        "category": "privacy",
        "description": "Widget de noticias en la barra de tareas de W10 (OFF = oculto)",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "search_highlights",
        "name": "Búsquedas Destacadas",
        "category": "privacy",
        "description": "Contenido web sugerido en el menú inicio (OFF = desactivado)",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    # ── Rendimiento ───────────────────────────────────────────────────────
    {
        "id": "startup_sound",
        "name": "Sonido de inicio de Windows",
        "category": "performance",
        "description": "Sonido al arrancar Windows (OFF = silenciado)",
        "risk": "low",
        "recommended": False,
        "gaming": True,
    },
    {
        "id": "visual_effects",
        "name": "Efectos visuales",
        "category": "performance",
        "description": "Animaciones y transparencias de Windows (OFF = mínimos, más rendimiento)",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "autoplay",
        "name": "Reproducción Automática",
        "category": "performance",
        "description": "AutoPlay de medios extraíbles (USB, DVD) al conectarlos (OFF = desactivado)",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "hibernation",
        "name": "Hibernación",
        "category": "performance",
        "description": "Archivo hiberfil.sys en disco (varios GB). OFF = eliminado, libera espacio",
        "risk": "medium",
        "recommended": False,
        "gaming": True,
    },
    # ── Gaming ────────────────────────────────────────────────────────────
    {
        "id": "game_mode",
        "name": "Modo Juego",
        "category": "gaming",
        "description": "Game Mode de Windows para priorizar recursos en juegos (ON = activo)",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "hardware_acceleration",
        "name": "GPU Scheduling (HAGS)",
        "category": "gaming",
        "description": "Planificación de GPU por hardware. En GPUs antiguas puede generar stuttering",
        "risk": "medium",
        "recommended": False,
        "gaming": False,
    },
    {
        "id": "timer_resolution",
        "name": "Resolución de Timer del Sistema",
        "category": "gaming",
        "description": "Timer de alta resolución para menor latencia en juegos (OFF = desactivado)",
        "risk": "medium",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "network_throttle",
        "name": "Throttling de Red para Juegos",
        "category": "gaming",
        "description": "Limitación del 20% de ancho de banda reservado del sistema (OFF = sin límite)",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    # ── Windows 11 only ───────────────────────────────────────────────────
    {
        "id": "w11_copilot_taskbar",
        "name": "Botón Copilot en barra de tareas",
        "category": "privacy",
        "description": "Icono de Copilot IA en la barra de tareas (OFF = oculto)",
        "risk": "low",
        "recommended": True,
        "gaming": True,
        "win11": True,
    },
    {
        "id": "w11_recall",
        "name": "Windows Recall",
        "category": "privacy",
        "description": "Recall guarda capturas de pantalla periódicas para búsqueda con IA. Serio riesgo de privacidad",
        "risk": "high",
        "recommended": True,
        "gaming": True,
        "win11": True,
    },
    {
        "id": "w11_ai_search",
        "name": "Búsqueda con IA mejorada",
        "category": "privacy",
        "description": "Sugerencias de búsqueda generadas por IA en el menú inicio y barra de búsqueda",
        "risk": "low",
        "recommended": True,
        "gaming": True,
        "win11": True,
    },
    {
        "id": "w11_widgets",
        "name": "Panel de Widgets (W11)",
        "category": "privacy",
        "description": "Panel lateral de widgets con noticias, clima y contenido personalizado por IA",
        "risk": "low",
        "recommended": True,
        "gaming": True,
        "win11": True,
    },
    {
        "id": "w11_snap_suggest",
        "name": "Sugerencias de Snap Layout",
        "category": "performance",
        "description": "W11 sugiere distribuciones de ventanas usando IA. Consume recursos en segundo plano",
        "risk": "low",
        "recommended": True,
        "gaming": True,
        "win11": True,
    },
    {
        "id": "w11_typing_insights",
        "name": "Estadísticas de escritura (Typing Insights)",
        "category": "privacy",
        "description": "Recopila datos de teclado para mejorar el autocompletado por IA (OFF = desactivado)",
        "risk": "low",
        "recommended": True,
        "gaming": True,
        "win11": True,
    },
    {
        "id": "w11_personalized_ads",
        "name": "Experiencias personalizadas (IA)",
        "category": "privacy",
        "description": "Usa datos de uso para personalizar sugerencias con IA en todo el sistema",
        "risk": "low",
        "recommended": True,
        "gaming": True,
        "win11": True,
    },
    {
        "id": "w11_voice_typing",
        "name": "Escritura por voz",
        "category": "privacy",
        "description": "El dictado por voz de W11 puede enviar audio a servidores de Microsoft",
        "risk": "medium",
        "recommended": True,
        "gaming": True,
        "win11": True,
    },
]

# Preset profiles (only base items, no W11-specific)
PRESET_PROFILES = {
    "gaming": {
        "name": "🎮 Gaming",
        "description": "Máximo rendimiento en juegos. Desactiva servicios innecesarios, telemetría y optimiza el sistema para gaming.",
        "apps":     [a["id"] for a in BLOATWARE_APPS if a.get("gaming", a["recommended"]) and not a.get("win11")],
        "services": [s["id"] for s in SERVICES if s.get("gaming", s["recommended"]) and not s.get("win11")],
        "tweaks":   [t["id"] for t in TWEAKS if t.get("gaming", t["recommended"]) and not t.get("win11")],
    },
    "trabajo": {
        "name": "💼 Trabajo",
        "description": "Elimina bloatware y telemetría manteniendo estabilidad. Conserva funciones útiles para el trabajo diario.",
        "apps":     [a["id"] for a in BLOATWARE_APPS if a["recommended"] and a["id"] not in ["xbox", "onenote", "your_phone"] and not a.get("win11")],
        "services": [s["id"] for s in SERVICES if s["recommended"] and s["risk"] != "high" and not s.get("win11")],
        "tweaks":   [t["id"] for t in TWEAKS if t["recommended"] and t["category"] in ["privacy", "performance"] and not t.get("win11")],
    },
    "minimo": {
        "name": "🧹 Mínimo",
        "description": "Solo elimina el bloatware más evidente. Cambios conservadores y seguros para cualquier usuario.",
        "apps":     [a["id"] for a in BLOATWARE_APPS if a["recommended"] and a["risk"] == "low" and not a.get("win11")],
        "services": [s["id"] for s in SERVICES if s["recommended"] and s["risk"] == "low" and not s.get("win11")],
        "tweaks":   [t["id"] for t in TWEAKS if t["recommended"] and t["risk"] == "low" and t["category"] == "privacy" and not t.get("win11")],
    },
}
