"""
All Windows 10 bloatware, services, and tweaks definitions.
"""

BLOATWARE_APPS = [
    {
        "id": "teams",
        "name": "Microsoft Teams",
        "package": "MicrosoftTeams",
        "description": "Aplicación de videoconferencias preinstalada",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "skype",
        "name": "Skype",
        "package": "Microsoft.SkypeApp",
        "description": "Cliente de videollamadas clásico de Microsoft",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "cortana",
        "name": "Cortana",
        "package": "Microsoft.549981C3F5F10",
        "description": "Asistente virtual de Microsoft",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "xbox",
        "name": "Xbox App",
        "package": "Microsoft.XboxApp",
        "description": "Aplicación de Xbox (no necesaria si no juegas en Xbox)",
        "risk": "low",
        "recommended": False,
    },
    {
        "id": "xbox_gamebar",
        "name": "Xbox Game Bar",
        "package": "Microsoft.XboxGamingOverlay",
        "description": "Overlay de juego con captura de pantalla y chat",
        "risk": "medium",
        "recommended": False,
    },
    {
        "id": "xbox_identity",
        "name": "Xbox Identity Provider",
        "package": "Microsoft.XboxIdentityProvider",
        "description": "Servicio de identidad de Xbox",
        "risk": "medium",
        "recommended": False,
    },
    {
        "id": "xbox_speech",
        "name": "Xbox Speech To Text",
        "package": "Microsoft.XboxSpeechToTextOverlay",
        "description": "Overlay de voz de Xbox",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "bing_weather",
        "name": "El Tiempo (MSN)",
        "package": "Microsoft.BingWeather",
        "description": "Widget del tiempo de Bing",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "bing_news",
        "name": "Noticias (MSN)",
        "package": "Microsoft.BingNews",
        "description": "Lector de noticias de Bing",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "bing_finance",
        "name": "Dinero (MSN)",
        "package": "Microsoft.BingFinance",
        "description": "App de finanzas de Bing",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "bing_sports",
        "name": "Deportes (MSN)",
        "package": "Microsoft.BingSports",
        "description": "App de deportes de Bing",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "solitaire",
        "name": "Microsoft Solitaire",
        "package": "Microsoft.MicrosoftSolitaireCollection",
        "description": "Colección de juegos de cartas",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "candy_crush",
        "name": "Candy Crush / King Games",
        "package": "king.com",
        "description": "Juegos de King preinstalados",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "3d_builder",
        "name": "3D Builder",
        "package": "Microsoft.3DBuilder",
        "description": "Aplicación de modelado 3D básico",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "3d_viewer",
        "name": "3D Viewer",
        "package": "Microsoft.Microsoft3DViewer",
        "description": "Visor de modelos 3D",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "mixed_reality",
        "name": "Mixed Reality Portal",
        "package": "Microsoft.MixedReality.Portal",
        "description": "Portal de realidad mixta (solo útil con hardware VR)",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "onenote",
        "name": "OneNote (Store)",
        "package": "Microsoft.Office.OneNote",
        "description": "Versión UWP de OneNote",
        "risk": "low",
        "recommended": False,
    },
    {
        "id": "maps",
        "name": "Mapas de Windows",
        "package": "Microsoft.WindowsMaps",
        "description": "App de mapas integrada",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "people",
        "name": "Contactos (People)",
        "package": "Microsoft.People",
        "description": "App de contactos integrada",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "get_started",
        "name": "Comenzar / Tips",
        "package": "Microsoft.Getstarted",
        "description": "App de bienvenida y tutoriales de Windows",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "feedback_hub",
        "name": "Centro de Opiniones",
        "package": "Microsoft.WindowsFeedbackHub",
        "description": "App para enviar feedback a Microsoft",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "print3d",
        "name": "Imprimir en 3D",
        "package": "Microsoft.Print3D",
        "description": "Herramienta de impresión 3D",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "groove_music",
        "name": "Groove Music",
        "package": "Microsoft.ZuneMusic",
        "description": "Reproductor de música de Microsoft",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "movies_tv",
        "name": "Películas y TV",
        "package": "Microsoft.ZuneVideo",
        "description": "Reproductor de vídeo de Microsoft",
        "risk": "low",
        "recommended": False,
    },
    {
        "id": "wallet",
        "name": "Microsoft Wallet",
        "package": "Microsoft.Wallet",
        "description": "Servicio de pagos de Microsoft",
        "risk": "low",
        "recommended": True,
    },
    {
        "id": "sticky_notes",
        "name": "Notas Rápidas",
        "package": "Microsoft.MicrosoftStickyNotes",
        "description": "Post-its digitales",
        "risk": "low",
        "recommended": False,
    },
    {
        "id": "alarms",
        "name": "Alarmas y Reloj",
        "package": "Microsoft.WindowsAlarms",
        "description": "App de alarmas del sistema",
        "risk": "low",
        "recommended": False,
    },
    {
        "id": "camera",
        "name": "Cámara",
        "package": "Microsoft.WindowsCamera",
        "description": "App de cámara integrada",
        "risk": "low",
        "recommended": False,
    },
    {
        "id": "your_phone",
        "name": "Tu Teléfono",
        "package": "Microsoft.YourPhone",
        "description": "Sincronización con teléfono Android",
        "risk": "low",
        "recommended": False,
    },
    {
        "id": "advertising_id",
        "name": "Microsoft Advertising",
        "package": "Microsoft.Advertising.Xaml",
        "description": "SDK de publicidad de Microsoft",
        "risk": "low",
        "recommended": True,
    },
]

SERVICES = [
    {
        "id": "diagtrack",
        "name": "Telemetría (DiagTrack)",
        "service": "DiagTrack",
        "description": "Recopila y envía datos de diagnóstico a Microsoft",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "dmwappushservice",
        "name": "WAP Push (dmwappushsvc)",
        "service": "dmwappushservice",
        "description": "Servicio de mensajes WAP, relacionado con telemetría",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "sysmain",
        "name": "SysMain (SuperFetch)",
        "service": "SysMain",
        "description": "Precarga aplicaciones en RAM. En SSDs puede perjudicar el rendimiento",
        "risk": "medium",
        "recommended": False,
        "gaming": True,
    },
    {
        "id": "wsearch",
        "name": "Windows Search",
        "service": "WSearch",
        "description": "Indexa archivos para búsqueda rápida. Consume CPU/disco en segundo plano",
        "risk": "medium",
        "recommended": False,
        "gaming": True,
    },
    {
        "id": "wuauserv",
        "name": "Windows Update",
        "service": "wuauserv",
        "description": "Servicio de actualizaciones automáticas",
        "risk": "high",
        "recommended": False,
        "gaming": False,
    },
    {
        "id": "bits",
        "name": "BITS (Transferencias en 2º plano)",
        "service": "BITS",
        "description": "Descarga actualizaciones en segundo plano",
        "risk": "medium",
        "recommended": False,
        "gaming": True,
    },
    {
        "id": "print_spooler",
        "name": "Cola de Impresión (Spooler)",
        "service": "Spooler",
        "description": "Gestiona las impresiones. Desactívalo si no tienes impresora",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "fax",
        "name": "Fax",
        "service": "Fax",
        "description": "Servicio de fax. Completamente innecesario en la mayoría de casos",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "remoteregistry",
        "name": "Registro Remoto",
        "service": "RemoteRegistry",
        "description": "Permite modificar el registro de forma remota. Riesgo de seguridad",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "lfsvc",
        "name": "Servicio de Geolocalización",
        "service": "lfsvc",
        "description": "Servicio de ubicación GPS del sistema",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "wbiosrvc",
        "name": "Biometría de Windows",
        "service": "WbioSrvc",
        "description": "Gestiona lectores de huella dactilar y reconocimiento facial",
        "risk": "low",
        "recommended": False,
        "gaming": False,
    },
    {
        "id": "icssvc",
        "name": "Zona de acceso móvil (Hotspot)",
        "service": "icssvc",
        "description": "Permite compartir conexión por WiFi desde el PC",
        "risk": "low",
        "recommended": False,
        "gaming": True,
    },
    {
        "id": "lmhosts",
        "name": "Ayuda de NetBIOS TCP/IP",
        "service": "lmhosts",
        "description": "Resolución de nombres NetBIOS en red local, obsoleto",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "tabletinputservice",
        "name": "Servicio de Panel Táctil",
        "service": "TabletInputService",
        "description": "Soporte para teclado táctil y escritura a mano. Innecesario sin pantalla táctil",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "xblauthmanager",
        "name": "Xbox Auth Manager",
        "service": "XblAuthManager",
        "description": "Autenticación de Xbox Live",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "xblgamesave",
        "name": "Xbox Live Game Save",
        "service": "XblGameSave",
        "description": "Sincroniza guardadas de Xbox Live",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "xboxnetapisvc",
        "name": "Xbox Network API",
        "service": "XboxNetApiSvc",
        "description": "API de red de Xbox Live",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "retaildemo",
        "name": "Modo Demo de Tienda",
        "service": "RetailDemo",
        "description": "Modo demostración de tienda. Completamente inútil en uso normal",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "mapsbrokersvc",
        "name": "Gestor de Mapas",
        "service": "MapsBroker",
        "description": "Descarga mapas offline para la app Mapas",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "sharedaccess",
        "name": "Conexión Compartida a Internet (ICS)",
        "service": "SharedAccess",
        "description": "Permite compartir la conexión a Internet entre equipos",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
]

TWEAKS = [
    {
        "id": "telemetry_reg",
        "name": "Desactivar telemetría (Registro)",
        "category": "privacy",
        "description": "Establece el nivel de telemetría a 0 (mínimo) en el registro",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "cortana_search",
        "name": "Desactivar Cortana en búsquedas",
        "category": "privacy",
        "description": "Desactiva la integración de Cortana en la barra de búsqueda",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "activity_history",
        "name": "Desactivar Historial de Actividad",
        "category": "privacy",
        "description": "Desactiva la línea de tiempo y el historial de actividad de Windows",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "advertising_id",
        "name": "Desactivar ID de Publicidad",
        "category": "privacy",
        "description": "Desactiva el identificador único de publicidad de Microsoft",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "location_tracking",
        "name": "Desactivar rastreo de ubicación",
        "category": "privacy",
        "description": "Desactiva el servicio de localización de Windows",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "feedback_freq",
        "name": "Desactivar solicitudes de Feedback",
        "category": "privacy",
        "description": "Impide que Windows pida valoraciones y opiniones periódicamente",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "startup_sound",
        "name": "Desactivar sonido de inicio de Windows",
        "category": "performance",
        "description": "Elimina el sonido al arrancar Windows",
        "risk": "low",
        "recommended": False,
        "gaming": True,
    },
    {
        "id": "game_mode",
        "name": "Activar Modo Juego",
        "category": "gaming",
        "description": "Activa el Game Mode de Windows para priorizar recursos en juegos",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "hardware_acceleration",
        "name": "Desactivar GPU Scheduling (HAGS)",
        "category": "gaming",
        "description": "En algunas GPUs antiguas HAGS puede generar stuttering. Desactívalo si notas problemas",
        "risk": "medium",
        "recommended": False,
        "gaming": False,
    },
    {
        "id": "power_plan",
        "name": "Plan de energía: Alto Rendimiento",
        "category": "performance",
        "description": "Cambia el plan de energía a Alto Rendimiento para máximo CPU",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "visual_effects",
        "name": "Reducir efectos visuales",
        "category": "performance",
        "description": "Desactiva animaciones y transparencias de Windows para liberar recursos",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "notifications",
        "name": "Desactivar notificaciones del sistema",
        "category": "privacy",
        "description": "Desactiva el centro de notificaciones y las notificaciones de apps",
        "risk": "low",
        "recommended": False,
        "gaming": True,
    },
    {
        "id": "autoplay",
        "name": "Desactivar Reproducción Automática",
        "category": "performance",
        "description": "Desactiva el AutoPlay de medios extraíbles (USB, DVD)",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "error_reporting",
        "name": "Desactivar Informes de Error de Windows",
        "category": "privacy",
        "description": "Impide el envío automático de informes de error a Microsoft",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "remote_assistance",
        "name": "Desactivar Asistencia Remota",
        "category": "privacy",
        "description": "Desactiva la función de asistencia remota de Windows",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "hibernation",
        "name": "Desactivar Hibernación",
        "category": "performance",
        "description": "Elimina el archivo hiberfil.sys y libera espacio en disco (varios GB)",
        "risk": "medium",
        "recommended": False,
        "gaming": True,
    },
    {
        "id": "news_interests",
        "name": "Desactivar Noticias e Intereses (Barra de Tareas)",
        "category": "privacy",
        "description": "Elimina el widget de noticias de la barra de tareas",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "search_highlights",
        "name": "Desactivar Búsquedas Destacadas",
        "category": "privacy",
        "description": "Desactiva las búsquedas sugeridas y contenido web en el menú inicio",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "timer_resolution",
        "name": "Resolución de Timer del Sistema",
        "category": "gaming",
        "description": "Reduce la resolución del timer del sistema para menor latencia en juegos",
        "risk": "medium",
        "recommended": True,
        "gaming": True,
    },
    {
        "id": "network_throttle",
        "name": "Desactivar Throttling de Red para Juegos",
        "category": "gaming",
        "description": "Desactiva la limitación de ancho de banda reservado del sistema (20%)",
        "risk": "low",
        "recommended": True,
        "gaming": True,
    },
]

# Preset profiles
PRESET_PROFILES = {
    "gaming": {
        "name": "🎮 Gaming",
        "description": "Máximo rendimiento en juegos. Desactiva servicios innecesarios, telemetría y optimiza el sistema para gaming.",
        "apps": [a["id"] for a in BLOATWARE_APPS if a.get("gaming", a["recommended"])],
        "services": [s["id"] for s in SERVICES if s.get("gaming", s["recommended"])],
        "tweaks": [t["id"] for t in TWEAKS if t.get("gaming", t["recommended"])],
    },
    "trabajo": {
        "name": "💼 Trabajo",
        "description": "Elimina bloatware y telemetría manteniendo estabilidad. Conserva funciones útiles para el trabajo diario.",
        "apps": [a["id"] for a in BLOATWARE_APPS if a["recommended"] and a["id"] not in ["xbox", "onenote", "your_phone"]],
        "services": [s["id"] for s in SERVICES if s["recommended"] and s["risk"] != "high"],
        "tweaks": [t["id"] for t in TWEAKS if t["recommended"] and t["category"] in ["privacy", "performance"]],
    },
    "minimo": {
        "name": "🧹 Mínimo",
        "description": "Solo elimina el bloatware más evidente. Cambios conservadores y seguros para cualquier usuario.",
        "apps": [a["id"] for a in BLOATWARE_APPS if a["recommended"] and a["risk"] == "low"],
        "services": [s["id"] for s in SERVICES if s["recommended"] and s["risk"] == "low"],
        "tweaks": [t["id"] for t in TWEAKS if t["recommended"] and t["risk"] == "low" and t["category"] == "privacy"],
    },
}
